-- # TABLE 10 - IMMUN_HCP_SEGMENT

CREATE OR REPLACE TABLE CBT_IMMUN_GASTRO_SEGMENT_ITMD AS
SELECT 
    TRIM(ABV_CUSTOMER_ID) AS ABV_CUSTOMER_ID,
	MAX(CASE WHEN UPPER(SEGMENT_NAME) = $GASTRO_SEGMENT_1 THEN SEGMENT_VALUE END) AS RINVOQ_UC_CD_HITS,
	MAX(CASE WHEN UPPER(SEGMENT_NAME) = $GASTRO_SEGMENT_2 THEN SEGMENT_VALUE END) AS SKYRIZI_UC_CD_HITS,
	MAX(CASE WHEN UPPER(SEGMENT_NAME) = $GASTRO_SEGMENT_3 THEN SEGMENT_VALUE END) AS GASTRO_SEGMENT,
	MAX(CASE WHEN UPPER(SEGMENT_NAME) = $GASTRO_SEGMENT_4 THEN SEGMENT_VALUE END) AS IBD_SEGMENT
FROM HBA.UDM_SEGMENTS
WHERE UPPER(SEGMENT_NAME) IN ($GASTRO_SEGMENT_1,$GASTRO_SEGMENT_2,$GASTRO_SEGMENT_3,$GASTRO_SEGMENT_4)
AND ADS_ACTIVE_FLAG = $ACTIVE_FLAG
AND SUBSCRIBER = $SUBSCRIBER_MABI
GROUP BY ABV_CUSTOMER_ID;